### ISSUE TITLE
Better logging for errors

### ISSUE THREAD

**Issue by susspectsoftware-dev** [bencuthbert001/Dao-builder#8]
When we have errors, we should throw better statements for logging this:

Exception in thread "main" java.lang.NullPointerException
	at com.sussoftware.daobuilder.DAOBuilder.buildDAO(DAOBuilder.java:86)
	at com.sussoftware.daobuilder.DAOBuilder.start(DAOBuilder.java:42)
	at com.sussoftware.daobuilder.DAOBuilder.main(DAOBuilder.java:73)

**Comment by susspectsoftware-dev** [comment]
1.16.0 fixes this issue.
